FROM kashu98/rag3d:latest

WORKDIR /app
RUN git clone https://github.com/graspnet/graspnet-baseline.git && \
    cd graspnet-baseline && \
    cd pointnet2 && \
    python setup.py install && \
    cd ../knn && \
    python setup.py install

RUN pip install transforms3d trimesh autolab_core autolab-perception \
    cvxopt grasp_nms
WORKDIR /workspace